# Generated by Django 2.2.13 on 2020-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200722_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст_Полный'),
        ),
    ]
