# Generated by Django 2.2.13 on 2020-07-28 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_text_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_2',
            new_name='text_full',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=None, verbose_name='Время создания'),
        ),
    ]
