# Generated by Django 2.2.13 on 2020-07-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_text_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_2',
            new_name='text_full',
        ),
    ]
