# Generated by Django 2.2.13 on 2020-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('moderated', 'В разработке'), ('rejected', 'Сделаные')], default='new', max_length=15, verbose_name='Модерация'),
        ),
    ]
